### ISSUE TITLE
 LTSP 5 Installation 

### ISSUE THREAD

**Issue by tichzvidzayi** [ltsp/ltsp5#1]
Hi All,

Is there still a way to install LTSP 5 Installation because it seems like the previous website has being taken down.??  http://wiki.ltsp.org/wiki/Installation/Ubuntu  

Regards.

Tichaona Zvidzayi

**Comment by alkisg** [comment]
Hi, LTSP5 is supported in its mailing list, not here: https://sourceforge.net/p/ltsp/mailman/

Its wiki has been moved to the wiki link above: https://github.com/ltsp/ltsp5/wiki

There were many notices about the old web site going down in the mailing list for the past 6 months.
